---
title: "Vignette"
format: html
editor: visual
---

## Introduction 

Para 1 - Automated testing is important for large scale data handling of observations.

Para 2 - There are a suite of tests of available for quality assurance. 

Para 3 - These do not necessarily guarantee the quality of the extreme observations. Known issues persist in this data. 

Para 4 - Here we provide methods and examples showing how to better assess the quality of the extremal observations. 

## Data 

* GHCNDaily data
* Variables 
* Flags 
* rnoaa download 

### Visualisation 

* 1974 example
* Highlight bad observations 

## Quality Control Issues

### Example Issue Write Up

* Explain the problem
* Identify and show examples of this quality control issue in the data
* Provide R function(s) to address the issue 
* Provide suggested updated quality flag 
* Depending on the issue, demonstrate the impact of this on a basic GEV analysis with and without the fix.

### Outliers vs Extremes

### Untagged Accumulations 

### Flagging systematic missingness

* (curious but aside - How does this carry through to the gridded data)

### Conclusions

### References
